import Link from "next/link";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service | ShambaIQ",
  description: "Terms and conditions for using ShambaIQ's farm planning, plant diagnosis, and AI agronomist services. Read before using our platform.",
  alternates: { canonical: "https://shambaiq.com/terms" },
  openGraph: { title: "Terms of Service | ShambaIQ", description: "Terms and conditions for using ShambaIQ's farm planning, plant diagnosis, and agronomist services.", url: "https://shambaiq.com/terms" },
  twitter: { card: "summary", title: "Terms of Service | ShambaIQ", description: "Terms and conditions for using ShambaIQ." },
};

const EFFECTIVE_DATE = "28 May 2026";
const CONTACT_EMAIL = "info@shambaiq.com";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display text-lg font-bold text-forest-700 mb-3 pb-2 border-b border-cream-300">{title}</h2>
      <div className="text-sm text-soil-600 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-cream-100">
      {/* Header */}
      <div className="bg-gradient-to-br from-forest-800 to-forest-700 text-white py-12 px-4 text-center">
        <div className="flex items-center justify-center gap-3 mb-3">
          <FileText size={28} className="text-gold-400" />
          <h1 className="font-display text-3xl font-bold">Terms of Service</h1>
        </div>
        <p className="text-cream-300 text-sm">Effective date: {EFFECTIVE_DATE}</p>
        <p className="text-cream-400 text-xs mt-1">Governed by the laws of Kenya</p>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-10">
        <div className="bg-white rounded-2xl shadow-sm border border-cream-300 px-6 sm:px-10 py-8">

          {/* AI Disclaimer — prominently first */}
          <div className="bg-amber-50 border border-amber-300 rounded-xl px-5 py-4 mb-8">
            <p className="text-amber-800 text-sm font-semibold mb-1">⚠️ Important: AI Advice Disclaimer</p>
            <p className="text-amber-700 text-sm leading-relaxed">
              All recommendations from ShambaIQ — including soil reports, fertilizer plans, plant disease diagnoses,
              and agronomist chat responses — are generated by AI and are <strong>advisory only</strong>. They do not
              replace advice from a qualified agronomist or your county agricultural extension officer. Always verify
              recommendations before applying inputs to your farm. ShambaIQ is not liable for crop losses, input
              costs, or any damages arising from reliance on AI-generated advice.
            </p>
          </div>

          <p className="text-sm text-soil-600 leading-relaxed mb-8">
            These Terms of Service ("Terms") govern your use of ShambaIQ, operated by Polycar Limited ("we", "us").
            By creating an account or using any feature of ShambaIQ, you agree to these Terms. If you do not agree,
            please do not use the platform.
          </p>

          <Section title="1. What ShambaIQ provides">
            <p>ShambaIQ is an agricultural decision-support platform for Kenyan farmers. It provides:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>AI-generated soil fertility reports and fertilizer recommendations by county and crop</li>
              <li>Plant disease and pest diagnosis from uploaded photos (Plant Doctor)</li>
              <li>AI agronomist chat — Shamba Mshauri — for farming questions</li>
              <li>Weather forecasts and planting advice</li>
              <li>Crop guides and agrovet directory</li>
            </ul>
            <p>
              These are <strong>informational tools</strong>, not professional agricultural consultancy. We do not
              guarantee specific crop yields or outcomes from following our recommendations.
            </p>
          </Section>

          <Section title="2. Your account">
            <p>To access personalised features you must register with your phone number. You are responsible for:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Keeping your login credentials secure</li>
              <li>All activity that occurs under your account</li>
              <li>Providing accurate information — entering false county or crop data will produce inaccurate recommendations</li>
            </ul>
            <p>
              You must be at least 18 years old to create an account. One account per person — you may not create
              multiple accounts to circumvent any limits.
            </p>
          </Section>

          <Section title="3. AI-generated content — limitations and your responsibility">
            <p>
              ShambaIQ uses Google Gemini AI for Plant Doctor, Shamba Mshauri, and fertilizer planning. AI systems
              can make mistakes. Specifically:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Plant disease diagnoses may be incorrect, especially from low-quality photos</li>
              <li>Fertilizer rates are estimates — actual requirements vary by soil lot, rainfall, and variety</li>
              <li>Product prices shown are approximate and change frequently</li>
              <li>Advice may not account for local pest resistance or recent disease outbreaks in your area</li>
            </ul>
            <p>
              <strong>Always cross-check with your county extension officer before purchasing inputs or treating crops.</strong>{" "}
              ShambaIQ provides a link to contact information for agricultural extension offices in all 47 counties.
            </p>
          </Section>

          <Section title="4. Acceptable use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the platform for any purpose other than legitimate agricultural decision-making</li>
              <li>Upload images that are not of plants or crops to Plant Doctor</li>
              <li>Attempt to circumvent rate limits, reverse-engineer the API, or scrape data at scale</li>
              <li>Impersonate another farmer or enter false farm data</li>
              <li>Use the platform to generate agricultural misinformation for distribution</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms without prior notice.
            </p>
          </Section>

          <Section title="5. Your data and content">
            <p>
              You own your farm data. Soil reports, diagnosis history, and field records belong to you.
              You can export or delete them at any time — see our{" "}
              <Link href="/privacy" className="text-forest-600 font-medium hover:underline">Privacy Policy</Link>.
            </p>
            <p>
              By using ShambaIQ, you grant us a limited licence to use aggregated, anonymised farm data to
              improve our soil models and AI recommendations. We will never sell individual farm data or use it
              to target you with advertising.
            </p>
          </Section>

          <Section title="6. Payments and free tier">
            <p>
              Core features — soil reports, fertilizer recommendations, and basic Plant Doctor — are currently
              free. If we introduce paid features, we will give at least 30 days notice to registered users
              before any free feature becomes paid.
            </p>
            <p>
              Where payments are processed, they are handled by third-party payment providers (such as M-PESA or
              Stripe). We do not store card or M-PESA PIN details.
            </p>
          </Section>

          <Section title="7. Limitation of liability">
            <p>
              To the maximum extent permitted by Kenyan law, ShambaIQ and Polycar Limited shall not be liable for:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Crop losses or reduced yields resulting from following AI recommendations</li>
              <li>Input costs (fertilizers, pesticides, seeds) purchased based on platform advice</li>
              <li>Loss of income due to platform downtime or incorrect diagnosis</li>
              <li>Any indirect, consequential, or special damages of any kind</li>
            </ul>
            <p>
              Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months
              before the claim arose (or KES 1,000 if you have not made any payment).
            </p>
          </Section>

          <Section title="8. Platform availability">
            <p>
              We aim for high availability but do not guarantee 100% uptime. The platform may be unavailable
              during maintenance, due to third-party API outages (e.g. Google Gemini, Open-Meteo weather), or
              for other reasons beyond our control.
            </p>
          </Section>

          <Section title="9. Changes to these terms">
            <p>
              We may update these Terms as the platform grows. We will notify registered users by SMS at least
              14 days before material changes take effect. Continued use of the platform after that date
              constitutes acceptance of the new terms.
            </p>
            <p>
              We will always maintain a changelog of what changed and when at the bottom of this page.
            </p>
          </Section>

          <Section title="10. Governing law and disputes">
            <p>
              These Terms are governed by the laws of Kenya. Any dispute shall first be referred to mediation.
              If mediation fails, disputes shall be resolved by the courts of Kenya.
            </p>
            <p>
              For any concern about these Terms, contact us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-forest-600 font-medium hover:underline">{CONTACT_EMAIL}</a>.
              We will respond within 14 days.
            </p>
          </Section>

          {/* Changelog */}
          <section className="mb-6">
            <h2 className="font-display text-lg font-bold text-forest-700 mb-3 pb-2 border-b border-cream-300">Changelog</h2>
            <div className="text-sm text-soil-500 space-y-1">
              <div className="flex gap-4">
                <span className="font-mono text-xs text-soil-500 shrink-0 pt-0.5">28 May 2026</span>
                <span>Initial version published.</span>
              </div>
            </div>
          </section>

          <div className="border-t border-cream-200 pt-6 mt-6 flex flex-col sm:flex-row gap-3 justify-between items-start sm:items-center">
            <Link href="/privacy" className="text-sm text-forest-600 font-semibold hover:text-forest-800 transition-colors">
              Read our Privacy Policy →
            </Link>
            <Link href="/" className="text-sm text-soil-500 hover:text-soil-600 transition-colors">
              ← Back to ShambaIQ
            </Link>
          </div>

        </div>
      </div>
    </div>
  );
}
